// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/php403/im/internal/logic/biz"
	"github.com/php403/im/internal/logic/conf"
	"github.com/php403/im/internal/logic/data"
	"github.com/php403/im/internal/logic/server"
	"github.com/php403/im/internal/logic/service"
	"github.com/php403/im/pkg/log"
)

// Injectors from wire.go:

func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUsercase(userRepo, logger)
	userService := service.NewUserService(userUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, logger, userService)
	grpcServer := server.NewGRPCServer(confServer, logger, userService)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
